// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// beta_starts
NumericVector beta_starts(const double& shape, const double& offset, const double& total0, const int& compartments);
RcppExport SEXP _estimatePMR_beta_starts(SEXP shapeSEXP, SEXP offsetSEXP, SEXP total0SEXP, SEXP compartmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const double& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const double& >::type total0(total0SEXP);
    Rcpp::traits::input_parameter< const int& >::type compartments(compartmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_starts(shape, offset, total0, compartments));
    return rcpp_result_gen;
END_RCPP
}
// constPMR_gammaN_ode
arma::mat constPMR_gammaN_ode(const std::vector<double>& x0, const double& cycleLength, const double& mu, const double& museq, const double& R, const int& n, const double& inflec, const double& max_t, const double& dt);
RcppExport SEXP _estimatePMR_constPMR_gammaN_ode(SEXP x0SEXP, SEXP cycleLengthSEXP, SEXP muSEXP, SEXP museqSEXP, SEXP RSEXP, SEXP nSEXP, SEXP inflecSEXP, SEXP max_tSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const double& >::type cycleLength(cycleLengthSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type museq(museqSEXP);
    Rcpp::traits::input_parameter< const double& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type inflec(inflecSEXP);
    Rcpp::traits::input_parameter< const double& >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< const double& >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(constPMR_gammaN_ode(x0, cycleLength, mu, museq, R, n, inflec, max_t, dt));
    return rcpp_result_gen;
END_RCPP
}
// extract_parms
NumericVector extract_parms(const NumericVector& parms, const double& I0, const double& pfCycleLength, const double& inflec, const double& ring_duration);
RcppExport SEXP _estimatePMR_extract_parms(SEXP parmsSEXP, SEXP I0SEXP, SEXP pfCycleLengthSEXP, SEXP inflecSEXP, SEXP ring_durationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< const double& >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< const double& >::type pfCycleLength(pfCycleLengthSEXP);
    Rcpp::traits::input_parameter< const double& >::type inflec(inflecSEXP);
    Rcpp::traits::input_parameter< const double& >::type ring_duration(ring_durationSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_parms(parms, I0, pfCycleLength, inflec, ring_duration));
    return rcpp_result_gen;
END_RCPP
}
// archer_fitN_odeint
SEXP archer_fitN_odeint(NumericVector parms, DataFrame data, const bool& geno, const double& I0, const double& pfCycleLength, const double& inflec, const double& ring_duration, const bool& circ_return, const bool& seq_return, const bool& ring_prop_return, const bool& output_full_return);
RcppExport SEXP _estimatePMR_archer_fitN_odeint(SEXP parmsSEXP, SEXP dataSEXP, SEXP genoSEXP, SEXP I0SEXP, SEXP pfCycleLengthSEXP, SEXP inflecSEXP, SEXP ring_durationSEXP, SEXP circ_returnSEXP, SEXP seq_returnSEXP, SEXP ring_prop_returnSEXP, SEXP output_full_returnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const bool& >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< const double& >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< const double& >::type pfCycleLength(pfCycleLengthSEXP);
    Rcpp::traits::input_parameter< const double& >::type inflec(inflecSEXP);
    Rcpp::traits::input_parameter< const double& >::type ring_duration(ring_durationSEXP);
    Rcpp::traits::input_parameter< const bool& >::type circ_return(circ_returnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type seq_return(seq_returnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type ring_prop_return(ring_prop_returnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type output_full_return(output_full_returnSEXP);
    rcpp_result_gen = Rcpp::wrap(archer_fitN_odeint(parms, data, geno, I0, pfCycleLength, inflec, ring_duration, circ_return, seq_return, ring_prop_return, output_full_return));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_estimatePMR_beta_starts", (DL_FUNC) &_estimatePMR_beta_starts, 4},
    {"_estimatePMR_constPMR_gammaN_ode", (DL_FUNC) &_estimatePMR_constPMR_gammaN_ode, 9},
    {"_estimatePMR_extract_parms", (DL_FUNC) &_estimatePMR_extract_parms, 5},
    {"_estimatePMR_archer_fitN_odeint", (DL_FUNC) &_estimatePMR_archer_fitN_odeint, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_estimatePMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
