# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Produce a vector of starting abundances based on a symmetrical beta distribution
#'
#' @param shape Single numeric giving the Beta distribution shape parameter.
#' @param offset Single numeric giving the Beta distribution offset parameter.
#' @param total0 Single numeric giving the total abundance across all stages.
#' @param compartments Integer giving the number of compartments for
#'     stage structure.
#'
#' @export
#'
beta_starts <- function(shape, offset, total0, compartments) {
    .Call(`_estimatePMR_beta_starts`, shape, offset, total0, compartments)
}

#' Run ODE for constant PMR and gamma N.
#'
#' @param x0 Initial conditions for all stages.
#' @param Maximum time point to simulate to.
#' @param Time step to use for ODE.
#'
#'
#' @export
#'
#' @return Numeric matrix where rows are time and columns are stages.
#'
constPMR_gammaN_ode <- function(x0, cycleLength, mu, museq, R, n, inflec, max_t, dt) {
    .Call(`_estimatePMR_constPMR_gammaN_ode`, x0, cycleLength, mu, museq, R, n, inflec, max_t, dt)
}

#' Extract parameters.
#'
#' @export
#'
extract_parms <- function(parms, I0 = NA_real_, pfCycleLength = NA_real_, inflec = NA_real_, ring_duration = NA_real_) {
    .Call(`_estimatePMR_extract_parms`, parms, I0, pfCycleLength, inflec, ring_duration)
}

#' Main optimization function for model with 5-8 parameters.
#'
#' @param parms A numeric vector of parameter values.
#' @param data A dataframe containing necessary data (columns
#'     `"Circ"` and `"ring_prop"`).
#' @param geno Decides which dataset is being optimized (if set as false,
#'     then the function is fitting the data from O'Donnell et al., Parasite
#'     Immunology, 2021; if set as true, then the function is fitting the data
#'     from Prior et al., Scientifc Reports, 2019).
#' @param I0 Single numeric indicating the initial population size.
#'     Defaults to `NA`, which results in it being extracted from `parms`.
#' @param pfCycleLength Single numeric indicating the cycle length.
#'     Defaults to `NA`, which results in it being extracted from `parms`.
#' @param inflec Single numeric indicating the inflection point.
#'     Defaults to `NA`, which results in it being extracted from `parms`.
#' @param ring_duration Single numeric indicating the ring duration.
#'     Defaults to `NA`, which results in it being extracted from `parms`.
#' @param circ_return Single logical indicating whether to output
#'     circulating iRBCs.
#'     Defaults to `FALSE`.
#' @param seq_return Single logical indicating whether to output
#'     sequestered iRBCs.
#'     Defaults to `FALSE`.
#' @param ring_prop_return Single logical indicating whether to output
#'     ring proportions.
#'     Defaults to `FALSE`.
#' @param output_full_return Single logical indicating whether to output
#'     full ODE output.
#'     Defaults to `FALSE`.
#'
#' @export
#'
archer_fitN_odeint <- function(parms, data, geno, I0 = NA_real_, pfCycleLength = NA_real_, inflec = NA_real_, ring_duration = NA_real_, circ_return = FALSE, seq_return = FALSE, ring_prop_return = FALSE, output_full_return = FALSE) {
    .Call(`_estimatePMR_archer_fitN_odeint`, parms, data, geno, I0, pfCycleLength, inflec, ring_duration, circ_return, seq_return, ring_prop_return, output_full_return)
}

